### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [popcopy/unit-4-game#1]
Html looks good for the most part, some rogue closing div tags that don't seem to correspond to anything else, could potentially cause some unwanted effects, definitely be more careful about that (or line up your indentation if they are supposed to be there and i'm missing the openers) and paragraphs probably shouldn't go in header tags like you have in your h5. CSS has some inconsistent indentation, and also your last rules all give the same value so intsead of #s1{rule1:value1} #s2{rule1:value1} #s3{rule1:value1} you should do #s1, #s2, #s3 {rule1:value1} if that makes sense.

As far as your jquery went, easy to understand and straight forward. And it works, so overall very good. My critiques would first of all be if you're declaring variables do it in the top of the scope block you are doing it in, and those 4 onclicks do pretty much the same thing, so it would be best to take the different values they apply and turn those into variables and make that one function that is called on each function, but that's just a bit higher level than what we've done so far. In code, you want to be as DRY (don't repeat yourself) as possible. Overall, great job!

Oh, lastly, don't leave your readme blank, it could be the homework assignment straight from what you were given or notes you want to put in about it or whatever thoughts you want to share about the project, but just don't leave it blank.

**Comment by popcopy** [comment]
ok i will work to fix those errors - thanks
